### ISSUE TITLE
`TransactionReceipt` should error when status is not `SUCCESS` and return a `TransactionReceipt` *within* the error

### ISSUE THREAD

**Issue by failfmi** [hashgraph/hedera-sdk-go#132]
When submitting a schedule sign transaction, which will not update the signatures of the scheduled transaction, the transaction response `GetReceipt` returns an error `exceptional receipt status NO_NEW_VALID_SIGNATURES`

1. The receipt request itself should not resolve with an error, but more like with a transaction receipt, which has the status

**Comment by failfmi** [comment]
Returns `exceptional receipt status SCHEDULE_ALREADY_EXECUTED` as well.

**Comment by mehcode** [comment]
This is by design. Any receipt status that is not `SUCCESS` is flagged as an error.

**Comment by failfmi** [comment]
How different is from [this](https://github.com/hashgraph/hedera-sdk-go/issues/131)?

**Comment by danielakhterov** [comment]
Going to hijack this issue. After further internal discussion I realized that what we should be doing, and what we should have been doing all along is returning an `ErrReceiptStatusError` with a complete `TransactionReceipt` for all statuses that are not `SUCCESS`. This means you'll need to cast the `err` to a `ErrHederaReceiptStatus` first, and then pull the receipt out of that structure. The reason we are doing this is because it's consistent with the other SDK's where the `TransactionReceipt` is inside the receipt error.
