### ISSUE TITLE
Query Account Balance not showing updated balance after transfer

### ISSUE THREAD

**Issue by raykhoaza** [hashgraph/hedera-sdk-go#555]
### Description

After I transferred some balance to another account, I checked the balance of the new account but it shows 0. I checked on dragonglass to see and I see the transfer listed on the transfers list for the token but not the all transactions list. Also can't see that token's balance on the account on the explorer. Wonder if this is related to this new change.
```AccountBalance.[tokens|tokenDecimals] use a mirror node query instead```
This is the token
https://testnet.dragonglass.me/hedera/tokens/0.0.47819476
and this is the account that I transferred the balance to
https://testnet.dragonglass.me/hedera/accounts/0.0.2225359

### Steps to reproduce

1. Create a fungible token and mint some amount
2. Transfer some amount to another account
3. Query the balance of the account transferred to and it should show up as 0

### Hedera network

testnet

### Version

v2.17.1

### Operating system

macOS

**Comment by danielakhterov** [comment]
> Also can't see that token's balance on the account on the explorer. Wonder if this is related to this new change. `AccountBalance.[tokens|tokenDecimals] use a mirror node query instead` 

That is correct. The SDK can no longer provide that information because the service nodes no longer return the data. As for mirror nodes, I'm going to assume that it takes some time before they're updated with your token transfers.

**Comment by SimiHunjan** [comment]
Did you check the balance of the account using the AccountBalanceQuery? Sometimes when you submit the request right after the transfer the node isn't up to date with the information. Try adding a sleep period for a second or 2 between transferring and requesting the updated account balance.

We are still returning the token balances - they are just being marked as deprecated because in the future we may not. 

The balances are updated every 15 minutes on mirror node explorers today so there is a delay there.

I see the token balance here https://hashscan.io/#/testnet/accountbalances/0.0.2225359. If you click on show all token balances and go to page 76.

**Comment by raykhoaza** [comment]
I just added a 10 seconds sleep between the transfer and the tokenBalanceQuery in my go test and it still failed. Actually I noticed that it's returning nil now (not sure if this is default value for 0 amount). Should I increase the sleep more?

**Comment by manishmarathe** [comment]
@danielakhterov - why is this ticket closed? This is a big blocker for us.

Querying a mirror node and having to wait for 15 minutes is unacceptable. If we are building a DApp on top of Hedera, we need to be able to give insight to our users within 2-3 seconds latency at most of what is happening. If a transaction is issued and if that is async, we need to be able to query it within an acceptable seconds latency.

Want to know how does Hedera scale then? Adding a node in the graph and pointers to a grow the DAG should be faster than mining a node which on a slowest network of Bitcoin also accomplishes in an average 10 min time.
