### ISSUE TITLE
Need way for SDK to deal with nodes that are unavailable

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-go#90]
(raised here, but the issue exists across JS/Java/Go)

**Problem Statement:**
The SDKs maintain a list of nodes, however nodes sometimes become unavailable, either temporarily or semi-permanently. In the event a node is unavailable, the SDKs will retry sending a transaction or query to the same node over and over again until the transaction's valid duration is exceeded. 
-This introduces unnecessary delays (more than 30s) in returning an error condition.
Upon receiving the error, the user of the SDK may retry, however it's possible the SDK will pick the same node again.

**Additional problem**
In the GO SDK, a repeated failure to connect to a node is reported as `TRANSACTION_EXPIRED` which while true, does hide the true nature of the error which is not an expiration due to time as would be reported by a pre-check, but an expiry that is the result of a node connectivity/node down issue.

**Proposals**
- Upon connection failure, remove the node from the list of nodes to pick from
* Optionally attempt to re-introduce the node if node list falls below low watermark, or after a period of time
- Return an error condition that clearly indicates a network connection error occurred
* Optionally add a Protobuf error code for use by the SDK (not for use by the hedera nodes) so that the SDK can continue to return Protobuf errors instead of throwing exceptions
- For queries/transactions that only have a single client signature, attempt to reconstruct the transaction/query with a new node, sign and execute. (after removing the offending node from the list)
- For transactions/queries that have an explicit signature from the client (or multiple), return an error (it's not reasonable to expect the SDK to re-sign these complex transactions).
- Provide examples that illustrate best practice in handling error (not in all examples, but maybe an example that serves this purpose alone)

**Comment by danielakhterov** [comment]
I believe this behavior is now implemented using your second proposal. What we do now is sort the node list each time a transaction is frozen or a query is executed. The way this node list is sorted is by using the node's use count, last used timestamp, and health. The nodes health is simply determined by if it has a `delayUntil` value in the future. This means that the nodes will be round robin'd as much as possible while also prioritizing healthy nodes. Bad nodes will also be retried every so often to determine if they're still down. 

> For queries/transactions that only have a single client signature, attempt to reconstruct the transaction/query with a new node, sign and execute. (after removing the offending node from the list)

We already build request for 1/3rd the network, are you proposing we should build requests for the entire network? To clarify the reason we build request for only 1/3rd the network is because _iirc_ Hedera Hashgraph Algorithm is byzantine fault tolerant which if I understand correctly means no more than 1/3rd the network can be down otherwise bad things could happen.

> Provide examples that illustrate best practice in handling error (not in all examples, but maybe an example that serves this purpose alone)

Having an example with several bad nodes is something we should definitely do in each SDK.
